"""
zones.the_void.objects
──────────────────────
Object templates for The Void zone.

Add an entry to TEMPLATES for every object that can appear in this zone.
The "class" key picks the instantiation class (Object / Item / Weapon).
Omitting "class" defaults to Object.

Call spawn(key) to get a fresh independent instance.
"""

from ashenmoor.world import Object, Container, Item, Weapon
from ashenmoor.world.zone import make_spawner

TEMPLATES: dict[str, dict] = {
    "sack_of_darkness": {
        "spawn_as": Container,
        "name": "a sack of &Xdarkness&N",
        "key_words": ("darkness", "sack"),
        "room_description": "A plain looking sack lies on the ground.",
        "description": "The bag looks simple. It is a brown canvas. When you look inside you see a &Xblack void&N.",
        "capacity": 1000.0,
        "weightless_capacity": 1000.0,
        "weight": 0,
        "is_open": True,
    },
    "sword_that_seals_the_darkness": {
        "spawn_as": Weapon,
        "name": "&CT&Bh&Ce &BS&Cw&Bo&Cr&Bd &Ct&Bh&Ca&Bt &CS&Be&Ca&Bl&Cs &Bt&Ch&Be &CD&Ba&Cr&Bk&Cn&Be&Cs&Bs&N",
        "key_words": ("sword", "seals", "darkness"),
        "room_description": "&CT&Bh&Ce &BS&Cw&Bo&Cr&Bd &Ct&Bh&Ca&Bt &CS&Be&Ca&Bl&Cs &Bt&Ch&Be &CD&Ba&Cr&Bk&Cn&Be&Cs&Bs&N lies here.\nIts light &Willuminates&N the ground around it.",
        "description": "The sword is beautiful. It was forged by the &GElves&N as a tool against the &rGreat Darkness&N. It glows softly with &Bbluish&N &Wlight&N",
        "weight": 2,
        "dice": "5d7",
        "hitroll": 5,
        "damroll": 5,
    },
    "hanging_tree": {
        "spawn_as": Object,
        "name": "The Hanging Tree",
        "key_words": ("tree", "hanging"),
        "room_description": "An &Xominous&N, sad looking tree towers above you.",
        "description": "A &Xhanging tree&N, where they strung up a man they say &rmurdered&N three.",
    },
    "pile_of_goo": {
        "spawn_as": Item,
        "name": "a pile of goo",
        "key_words": ("pile", "goo"),
        "room_description": "A pile of &mgoo&N lies on the ground.",
        "description": "The goo is slightly, and disgustingly, warm. It has an odd, mildewy scent.",
    },
    "falcon_feather": {
        "spawn_as": Item,
        "name": "a falcon feather",
        "key_words": ("feather", "falcon"),
        "room_description": "A &xdark&N colored feather lies on the ground.",
        "description": "The feather is dark, from a falcon.",
    },
    "ethereal_sword": {
        "spawn_as": Weapon,
        "name": "an &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &ms&N&Mw&N&mo&N&Mr&N&md&N",
        "key_words": ("sword", "ethereal"),
        "room_description": "A &msword&N is stuck into the ground.",
        "description": "This sword was built to fight against the &Xdarkest enemies&N. It was once wielded by a great warrior.",
        "proc": "ethereal_sword",
        "weight": 2,
        "dice": "4d8",
        "hitroll": 5,
        "damroll": 5,
    },
    "ethereal_shield": {
        "spawn_as": Item,
        "name": "an &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &ms&N&Mh&N&mi&N&Me&N&ml&N&Md&N",
        "key_words": ("shield"),
        "room_description": "A shield rests here.",
        "description": "An interesting shield made of &Xdark colored wood&N and &ma purple dragon head&N drawn on it.",
        "wear_on": "secondary_hand",
        "is_shield": True,
        "dice": "2d4",
        "hitroll": 0,
        "damroll": 0,
        "ac_bonus": 10,
        "weight": 6,
        "cost": 100,
        "stat_mods": {},
        "save_mods": {},
    },
    "ethereal_cloak": {
        "spawn_as": Item,
        "name": "an &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &mc&N&Ml&N&mo&Ma&N&mk&N",
        "key_words": ("ethereal", "cloak"),
        "room_description": "A discarded cloak lies on the ground.",
        "description": "There is nothing special about the cloak, yet you seem to feel a presence of &bdark magic&N.",
        "wear_on": "about_body",
        "weight": 10.0,
        "cost": 200,
        "ac_bonus": 10,
        "stat_mods": {"dex": 10},
        "save_mods": {},
    },
    "ethereal_boots": {
        "spawn_as": Item,
        "name": "a pair of &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &mb&N&Mo&N&mo&N&Mt&N&ms&N",
        "key_words": ("ethereal", "boots"),
        "room_description": "A pair of boots lie discarded on the ground.",
        "description": "These boots shimmer with moonlight. They seem to empower you with confidence",
        "wear_on": "feet",
        "weight": 10.0,
        "cost": 200,
        "ac_bonus": 10,
        "stat_mods": {"dex": 10},
        "save_mods": {},
    },
    "ethereal_helmet": {
        "spawn_as": Item,
        "name": "an &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &mh&N&Me&N&ml&N&Mm&N&me&N&Mt&N",
        "key_words": ("ethereal", "helmet"),
        "room_description": "A helmet is dropped here.",
        "description": "The helmet's soft glow is captivating, and you feel stronger with it in your hands",
        "wear_on": "head",
        "weight": 10.0,
        "cost": 200,
        "ac_bonus": 10,
        "stat_mods": {"dex": 10},
        "save_mods": {},
    },
    "ethereal_visor": {
        "spawn_as": Item,
        "name": "an &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &mv&N&Mi&N&ms&N&Mo&N&mr&N",
        "key_words": ("ethereal", "visor"),
        "room_description": "A visor lies on the ground.",
        "description": "The visor's glass is shiny, and when you look through it the room around you gets &Wbrighter&N",
        "wear_on": "face",
        "weight": 2.0,
        "cost": 50,
        "ac_bonus": 5,
        "stat_mods": {"dex": 10},
        "save_mods": {},
    },
    "ethereal_amulet": {
        "spawn_as": Item,
        "name": "an &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &ma&N&Mm&N&mu&N&Ml&N&me&N&Mt&N",
        "key_words": ("ethereal", "amulet"),
        "room_description": "A necklace is strewn on the ground.",
        "description": "The &mpurple&N stone glows softly and the silver chain is comfortable and cool in your fingers",
        "wear_on": "neck",
        "weight": 2.0,
        "cost": 200,
        "ac_bonus": 5,
        "stat_mods": {"dex": 10},
        "save_mods": {},
    },
    "ethereal_breastplate": {
        "spawn_as": Item,
        "name": "an &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &mb&N&Mr&N&me&N&Ma&N&ms&N&Mt&N&mp&N&Ml&N&ma&N&Mt&N&me&N",
        "key_words": ("ethereal", "breastplate"),
        "room_description": "A shimmering breastplate lies here.",
        "description": "The breastplate's color is hypnotizing, and a great feeling of power emanates from it",
        "wear_on": "on_body",
        "weight": 20,
        "cost": 250,
        "ac_bonus": 10,
        "stat_mods": {"dex": 10},
        "save_mods": {},
    },
    "ethereal_sleeves": {
        "spawn_as": Item,
        "name": "a pair of &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &ms&N&Ml&N&me&N&Me&N&mv&N&Me&N&ms&N",
        "key_words": ("ethereal", "sleeves"),
        "room_description": "A pair of wadded up sleeves is thrown on the ground.",
        "description": "The sleeves's cloth smells heavenly, and the soft cloth is comfortable.",
        "wear_on": "arms",
        "weight": 5,
        "cost": 150,
        "ac_bonus": 10,
        "stat_mods": {"dex": 10},
        "save_mods": {},
    },
    "ethereal_gloves": {
        "spawn_as": Item,
        "name": "a pair of &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &mg&N&Ml&N&mo&N&Mv&N&me&N&Ms&N",
        "key_words": ("ethereal", "gloves"),
        "room_description": "A pair of wadded up gloves is trampled into the ground.",
        "description": "The pair's softness surprise you, because the material appears to be hard leather",
        "wear_on": "hands",
        "weight": 5,
        "cost": 150,
        "ac_bonus": 10,
        "stat_mods": {"dex": 10},
        "save_mods": {},
    },
    "ethereal_belt": {
        "spawn_as": Item,
        "name": "an &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &mb&N&Me&N&ml&N&Mt&N",
        "key_words": ("ethereal", "belt"),
        "room_description": "A belt has been carelessly left on the ground.",
        "description": "The belt is sturdy and strong, and is soft.",
        "wear_on": "waist",
        "weight": 10,
        "cost": 150,
        "ac_bonus": 10,
        "stat_mods": {"dex": 10},
        "save_mods": {},
    },
    "ethereal_grieves": {
        "spawn_as": Item,
        "name": "a pair of &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &mg&N&Mr&N&mi&N&Me&N&mv&N&Me&N&ms&N",
        "key_words": ("ethereal", "grieves"),
        "room_description": "A pair of grieves rests here.",
        "description": "The pair of pale leg coverings are cold to the touch.",
        "wear_on": "legs",
        "weight": 10,
        "cost": 150,
        "ac_bonus": 10,
        "stat_mods": {"dex": 10},
        "save_mods": {},
    },
    "ethereal_bracelet": {
        "spawn_as": Item,
        "name": "an &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &mb&N&Mr&N&ma&N&Mc&N&me&N&Ml&N&me&N&Mt&N",
        "key_words": ("ethereal", "bracelet"),
        "room_description": "A bracelet is shoved into the ground.",
        "description": "The bracelet is silver with a &mpurple&N stone in the middle that glows softly",
        "wear_on": "wrist",
        "weight": 5,
        "cost": 250,
        "ac_bonus": 10,
        "stat_mods": {"dex": 10},
        "save_mods": {},
    },
    "ethereal_earring": {
        "spawn_as": Item,
        "name": "an &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N&Ml&N &me&N&Ma&N&mr&N&Mr&N&mi&N&Mn&N&mg&N",
        "key_words": ("ethereal", "earring"),
        "room_description": "An earring is hidden on the ground.",
        "description": "The earring is small, with a glowing &mpurple&N stone.",
        "wear_on": "earring",
        "weight": 2,
        "cost": 250,
        "ac_bonus": 10,
        "stat_mods": {"dex": 10},
        "save_mods": {},
    },
    "ethereal_ring": {
        "spawn_as": Item,
        "name": "an &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N &mr&N&Mi&N&mn&N&Mg&N",
        "key_words": ("ethereal", "ring"),
        "room_description": "A ring is tossed on the ground.",
        "description": "The ring is small with a silver band and a glowing &mpurple&N stone.",
        "wear_on": "ring",
        "weight": 2,
        "cost": 250,
        "ac_bonus": 10,
        "stat_mods": {"dex": 10},
        "save_mods": {},
    },
    "shadow_chest": {
        "spawn_as":        Container,
        "name":            "&Xa shadow chest&N",
        "key_words":       ("chest", "shadow"),
        "room_description":"A dark wooden chest rests here.",
        "no_take":         True,
        "is_open":         False,
        "locked":          True,
        "key_name":        "shadow key",
        "capacity":        1000,
        "weight":          1,
        "contents": [
            "ethereal_boots", "ethereal_cloak", "ethereal_sword", "ethereal_sword", "ethereal_shield", "ethereal_helmet", "ethereal_visor", "ethereal_amulet", "ethereal_breastplate",
            "ethereal_sleeves", "ethereal_gloves", "ethereal_belt", "ethereal_grieves", "ethereal_bracelet", "ethereal_earring", "ethereal_ring", "ethereal_sack",   
        ],
    },
    "shadow_key": {
        "spawn_as":        Item,
        "name":            "&Xa shadow key&N",
        "key_words":       ("key", "shadow",),
        "room_description":"A key lies here.",
        "is_key":          True,
        "key_name":        "shadow key",
        "weight":          0.1,
    },
    "ethereal_sack": {
        "spawn_as":            Container,
        "name":                "an &me&N&Mt&N&mh&N&Me&N&mr&N&Me&N&ma&N &ms&N&Ma&N&mc&N&Mk&N",
        "key_words":           ("ethereal", "vault"),
        "room_description":    "A sack lies on the ground.",
        "description":         "A pale sack that seems to be woven from beams of moonlight.",
        "capacity":            1000.0,
        "weightless_capacity": 1000.0,
        "weight":              0,
        "is_open":             True,
    },
}

# Module-level spawn — rooms.py calls  O.spawn("red_marker")
spawn = make_spawner(TEMPLATES, lambda: Object)
